apiVersion: v1
kind: Pod
metadata:
  name: mpi-scheduler
  labels:
    name: mpi-scheduler
spec:
  hostname: mpi-scheduler
  subdomain: mpi-cluster
  containers:
  - image: hannahnw124/slurm_sing_mpi_ctl
    name: mpi-scheduler
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-0
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-0
  subdomain: mpi-cluster
  containers:
  - image: hannahnw124/slurm_sing_mpi_1
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-1
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-1
  subdomain: mpi-cluster
  containers:
  - image: hannahnw124/slurm_sing_mpi_1
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-2
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-2
  subdomain: mpi-cluster
  containers:
  - image: hannahnw124/slurm_sing_mpi_1
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Pod
metadata:
  name: mpi-worker-3
  labels:
    name: mpi-worker
spec:
  hostname: mpi-worker-3
  subdomain: mpi-cluster
  containers:
  - image: hannahnw124/slurm_sing_mpi_1
    name: mpi-worker
    securityContext:
      privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-cluster
spec:
  selector:
    name: mpi-worker
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mpi-scheduler
spec:
  selector:
    name: mpi-scheduler
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
